# Generated by Django 4.0.5 on 2023-02-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_reporter', '0002_manufacturer_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='omsid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='parts_usage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='store_sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='store_so_sku',
            field=models.CharField(max_length=50),
        ),
    ]
