# Generated by Django 4.1.6 on 2023-02-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_reporter', '0003_alter_manufacturer_model_alter_manufacturer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='name',
            new_name='vendor',
        ),
    ]
