# Generated by Django 3.2.18 on 2023-04-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_reporter', '0005_manufacturer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
