# Generated by Django 3.2.18 on 2023-04-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_reporter', '0008_auto_20230429_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
