# Generated by Django 3.2.18 on 2023-05-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_reporter', '0010_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='feedback',
        ),
    ]
