# Generated by Django 3.1.13 on 2023-08-05 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders_reporter', '0012_auto_20230804_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='order_date',
            new_name='date_of_production',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='parts',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='order_number',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='quantity',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
